Updated aoc-hs for new structure

diff --git a/aoc-hs b/aoc-hs
--- a/aoc-hs
+++ b/aoc-hs
@@ -1,14 +1,16 @@
 #!/bin/bash
+set -Eeuo
 
 YEAR=2025
 AOC_BASE_URL="https://adventofcode.com/${YEAR}"
 
 # Function to create a new Advent of Code solution for a given day
 create_new_solution() {
-  local number="$1"
-  local d="day-$(printf '%02d' ${number})"
+  local day="$1"
+  local padded_day
+  padded_day="$(printf '%02d' ${number})"
 
-  echo "Creating a new Advent of Code template for day $number."
+  echo "Creating a new Advent of Code template for day ${day}."
 
   if [ -f "./.env" ]; then
     echo "found .env file..."
@@ -17,8 +19,8 @@ create_new_solution() {
   fi
 
   # Create a directory for the day
-  mkdir -p inputs
-  mkdir -p src
+  mkdir -p solutions/inputs
+  mkdir -p solutions/src
 
   # Create the Haskell solution file
   module_template="module Main where
@@ -66,10 +68,10 @@ main = do
 "
   echo Creating files...
 
-  echo "$module_template" > "./src/$d.hs"
+  echo "$module_template" > "./solutions/src/${padded_day}.hs"
 
   # Create an empty input file
-  touch "./inputs/$d.example"
+  touch "./solutions/inputs/${padded_day}-ex.txt"
 
   # Download the input data from Advent of Code
   if [ "$download" == true ]; then
@@ -80,28 +82,26 @@ main = do
       read -r AOC_SESSION
     fi
 
-    curl -o "./inputs/$d.input" --cookie "session=${AOC_SESSION}" -A "curl-aoc" ${AOC_BASE_URL}/day/${number}/input
+    curl -o "./solutions/inputs/${padded_day}.txt" --cookie "session=${AOC_SESSION}" -A "curl-aoc" "${AOC_BASE_URL}/day/${day}/input"
   else
-    touch "./inputs/$d.input"
+    touch "./solutions/inputs/${padded_day}.txt"
   fi
 
   # Append the day to the advent-of-code.cabal file
-  cabal_day="executable ${d}
-  import: deps
-  hs-source-dirs:
-      src
-  main-is: ${d}.hs
+  cabal_day="executable day-${padded_day}
+  import: day
+  main-is: ${padded_day}.hs
 "
-  echo "$cabal_day" >> advent-of-code.cabal
+  echo "$cabal_day" >> solutions/solutions.cabal
 
-  echo "Created a new Advent of Code solution for day $number."
+  echo "Created a new Advent of Code solution for day ${day}"
 }
 
 run_solution() {
   local number="$1"
   local part="$2"
   local file_name="$3"
-  local d="day-$number"
+  local exe_file="day-$number"
 
   # Check if the file exists
   if [ ! -f "$file_name" ]; then
@@ -111,7 +111,7 @@ run_solution() {
 
   # Check if the number is a positive integer
   if ! [[ "$number" =~ ^(0[1-9]|1[0-2])$ ]]; then
-    echo "Invalid day: $number. It should be between 1 and 25"
+    echo "Invalid day: $number. It should be between 1 and 12"
     exit 1
   fi
 
@@ -121,99 +121,107 @@ run_solution() {
     exit 1
   fi
 
-  cabal run "$d" -- "$part" "$file_name"
+  cabal run "$exe_file" -- "$part" "$file_name"
 }
 
-# Check if the first argument is a subcommand and shift it out
-if [ "$1" == "new" ] || [ "$1" == "run" ]; then
-  subcommand="$1"
-  shift
-fi
+main() {
+  local subcommand
+  local number
+  local padded_number
+  local run_command
+  local run_filename
+  local part
 
-while getopts ":d:-:f:ei:p:" opt; do
-  case $opt in
-    d)
-      number="$OPTARG"
-      ;;
-    f)
-      run_command=f
-      run_filename="$OPTARG"
-      ;;
-    e)
-      run_command=example
-      ;;
-    i)
+  # Check if the first argument is a subcommand and shift it out
+  if [ "$1" == "new" ] || [ "$1" == "run" ]; then
+    subcommand="$1"
+    shift
+  fi
+
+  while getopts ":d:-:f:ei:p:" opt; do
+    case $opt in
+      d)
+        number="${OPTARG}"
+        padded_number=$(printf '%02d' "${number}")
+        ;;
+      f)
+        run_command=f
+        run_filename="$OPTARG"
+        ;;
+      e)
+        run_command=example
+        ;;
+      i)
+        run_command=input
+        ;;
+      -)
+        run_command="$OPTARG"
+        ;;
+      p)
+        part="$OPTARG"
+        ;;
+      \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+      :)
+        echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
+    esac
+  done
+
+  # Now you can check the parsed options and execute the corresponding actions.
+  if [ "$subcommand" == "new" ]; then
+    if [ -z "$number" ]; then
+      echo "Missing day for 'new' command."
+      exit 1
+    fi
+
+    if [ -z "$run_command" ]; then
+      download=true
+    fi
+
+    case "$run_command" in
+      no-curl)
+        download=false
+        ;;
+    esac
+
+    create_new_solution "$number"
+
+  elif [ "$subcommand" == "run" ]; then
+    if [ -z "$number" ]; then
+      echo "Missing day for 'run' command. Use option -d <day-number>"
+      exit 1
+    fi
+
+    if [ -z "$part" ]; then
+      echo "Missing part for 'run' command. Use option -p <part-number>"
+      exit 1
+    fi
+
+    if [ -z "$run_command" ]; then
+      # Default to '--input' if no filename is provided
       run_command=input
-      ;;
-    -)
-      run_command="$OPTARG"
-      ;;
-    p)
-      part="$OPTARG"
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-      ;;
-  esac
-done
+    fi
 
-# Now you can check the parsed options and execute the corresponding actions.
-if [ "$subcommand" == "new" ]; then
-  if [ -z "$number" ]; then
-    echo "Missing day for 'new' command."
-    exit 1
-  fi
+    case "$run_command" in
+      example)
+        run_filename="./solutions/inputs/$number-ex.txt"
+        ;;
+      input)
+        run_filename="./solutions/inputs/$number.txt"
+        ;;
+      f) ;;
+      *)
+        echo "unknown file. Use -f <file-path> for custom files"
+    esac
 
-  if [ -z "$run_command" ]; then
-    download=true
-  fi
+    run_solution "$padded_number" "$part" "$run_filename"
 
-  case "$run_command" in
-    no-curl)
-      download=false
-      ;;
-  esac
-
-  create_new_solution "$number"
-
-elif [ "$subcommand" == "run" ]; then
-  if [ -z "$number" ]; then
-    echo "Missing day for 'run' command. Use option -d <day-number>"
-    exit 1
-  fi
-
-  if [ -z "$part" ]; then
-    echo "Missing part for 'run' command. Use option -p <part-number>"
-    exit 1
-  fi
-
-  if [ -z "$run_command" ]; then
-    # Default to '--input' if no filename is provided
-    run_command=input
-  fi
-
-  case "$run_command" in
-    example)
-      run_filename="./inputs/day-$number.example"
-      ;;
-    input)
-      run_filename="./inputs/day-$number.input"
-      ;;
-    f) ;;
-    *)
-      echo "unknown file. Use -f <file-path> for custom files"
-  esac
-
-  run_solution "$number" "$part" "$run_filename"
-
-else
-  echo "Usage: aoc-hs [new -d <day> [--no-curl] | run -d <day> -p <part> [-f <file-name> | --example | -e | --input | -i]]
-
+  else
+    echo "Usage: aoc-hs [new -d <day> [--no-curl] | run -d <day> -p <part> [-f <file-name> | --example | -e | --input | -i]]
 
 Description:
   This tool simplifies Advent of Code solutions in Haskell by creating templates and handling input files. No need to learn Cabal!
@@ -247,5 +255,8 @@ Options:
   --example, -e  Use the example input file (./inputs/day-<day>.example) as input.
   --input, -i    (Default) Use the puzzle input file (./inputs/day-<day>.input) as input.
 "
-  exit 1
-fi
+    exit 1
+  fi
+}
+
+main "$@"
